# ============================================================
# 开发环境配置
# ============================================================

spring:
  # 数据源配置
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/xiaozhi-java?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: xiaozhi
    password: 123456

  # Neo4j 配置
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 12345678

# 本地环境邮箱配置
email:
  smtp:
    username: xxx
    password: xxx

dashscope:
  api:
    key: xxx
logging:
  level:
    root: INFO
    org.springframework: INFO
    io.github.imfangs.dify.client.impl.StreamEventDispatcher: ERROR
    io.netty.handler: ERROR
    com.xiaozhi: debug